name: Theme A
on:
  pull_request:
  push:
    branches:
      - main
      - 'renovate/*'
    paths:
      - 'themes/theme-a/**'
      - '.github/workflows/a.yml'

jobs:
  test:
      name: Test
      runs-on: ubuntu-latest
      if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
      steps:
        - uses: actions/checkout@v3
        - run: yarn
  subtree:
    name: Subtree
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          repo: 'minimaluminium/child'
          path: 'themes/theme-a'
          deploy_key: ${{secrets.LULZ_GITHUB_DEPLOY_KEY}}
          force: true